name: build
on:
  push:
    branches:
      - "main"
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: galexrt
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Quay.io Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_QUAYIO_USERNAME }}
          password: ${{ secrets.REGISTRY_QUAYIO_PASSWORD }}
      - name: Build Container Image
        run: |
          if [[ "${GITHUB_REF}" =~ ^refs/tags/* ]]; then
              # Tags
              VERSION="${GITHUB_REF/refs\/tags\//}"
          else
              # Branch
              VERSION="${GITHUB_REF/refs\/heads\//}"
          fi
          
          make container-build container-push VERSION="${VERSION:-main}"
